<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-05-19T15:24:15Z" name="Suite" finished-at="2024-05-19T15:24:35Z" duration-ms="20705">
    <groups>
    </groups>
    <test started-at="2024-05-19T15:24:15Z" name="Login" finished-at="2024-05-19T15:24:32Z" duration-ms="17723">
      <class name="Tests.Login">
        <test-method is-config="true" signature="lanchApplication()[pri:0, instance:Tests.Login@1c80e49b]" started-at="2024-05-19T15:24:15Z" name="lanchApplication" finished-at="2024-05-19T15:24:26Z" duration-ms="11335" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lanchApplication -->
        <test-method signature="login(java.util.HashMap)[pri:0, instance:Tests.Login@1c80e49b]" started-at="2024-05-19T15:24:26Z" name="login" data-provider="getData" finished-at="2024-05-19T15:24:32Z" duration-ms="5696" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=tms4us, email=superUser}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:Tests.Login@1c80e49b]" started-at="2024-05-19T15:24:32Z" name="closeBrowser" finished-at="2024-05-19T15:24:32Z" duration-ms="340" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- Tests.Login -->
    </test> <!-- Login -->
    <test started-at="2024-05-19T15:24:15Z" name="LoginandError" finished-at="2024-05-19T15:24:35Z" duration-ms="20705">
      <class name="Tests.LoginError">
        <test-method is-config="true" signature="lanchApplication()[pri:0, instance:Tests.LoginError@3f1c5af9]" started-at="2024-05-19T15:24:15Z" name="lanchApplication" finished-at="2024-05-19T15:24:28Z" duration-ms="13295" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- lanchApplication -->
        <test-method signature="loginError(java.util.HashMap)[pri:0, instance:Tests.LoginError@3f1c5af9]" started-at="2024-05-19T15:24:28Z" name="loginError" data-provider="getData" finished-at="2024-05-19T15:24:35Z" duration-ms="6663" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=1234, email=Anil}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [There is an error in the email or password] but found [There an error in the email or password]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [There is an error in the email or password] but found [There an error in the email or password]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Tests.LoginError.loginError(LoginError.java:20)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:40)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:489)
at org.testng.internal.thread.ThreadUtil$1.call(ThreadUtil.java:52)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginError -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:Tests.LoginError@3f1c5af9]" started-at="2024-05-19T15:24:35Z" name="closeBrowser" finished-at="2024-05-19T15:24:35Z" duration-ms="202" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- Tests.LoginError -->
    </test> <!-- LoginandError -->
  </suite> <!-- Suite -->
</testng-results>
